### PR TITLE
Set max string buffer to 0xFFF wide characters (issue #278)

### PR DESCRIPTION
**Pull request by amullins83**

### CODE REVIEW

**Comment by signal11** [comment]
This looks good

**Comment by signal11** [comment]
By good I mean the change.  Your commits are a mess, but I can work them out.

When you pull, if you pull --rebase then you won't get merge commits. You typically don't want to have your own merge commits on a trunk that tracks a remote.

**Comment by amullins83** [comment]
Apologies for the mixup. I forgot to pull upstream before editing and pushing to my fork.

**Comment by NicoHood** [comment]
On github you can merge them in a single commit. Just click the submenu when merging.

**Comment by signal11** [comment]
pushed 901512e88b8bac06d1402

I changed it to use a local MIN() instead of relying on the system-defined non-standard min() (from stdlib.h), and moved the #define to the top of the file. Also added some text to the commit message.

Thanks for finding this!

**Pull request closed without merging**
