### PR TITLE
initialize wstr for unusual windows drivers

### PR DESCRIPTION
**Pull request by JosepMaJAZ**
initialize wstr for unusual windows drivers that don't initialize it correctly even when returning TRUE

Issue #315

### CODE REVIEW

**Comment by Be-ing** [comment]
@JosepMaJAZ signal11 has abandoned hidapi. It is now maintained at https://github.com/libusb/hidapi . Can you reopen your pull request there?

**Comment by centic9** [comment]
Would be nice if you can state that on the main page/readme as otherwise people will continue to use this outdated version, at least I did.

**Comment by Youw** [comment]
That it not possible - no one has write access to this repo.

**Comment by JosepMaJAZ** [comment]
Closed. Implemented in libusb/hidapi

**Pull request closed without merging**
